In [93]:
import librosa 
import numpy as np
import os

In [94]:
dataset_path = r"C:\Users\Avi Mishra\OneDrive\Desktop\SAE"

In [95]:
X = []
y =[]

In [96]:
def feature_extract(file_path , class_name):

    audio , sr = librosa.load(file_path)
    mfcc = librosa.feature.mfcc(
           y = audio ,
           sr = sr ,
           n_mfcc = 40
    )

    feature = np.mean(mfcc , axis = 1)

    X.append(feature)
    y.append(class_name)
    

In [97]:
for label in os.listdir(dataset_path):

    class_path = os.path.join(dataset_path , label)

    exist_class = os.path.isdir(class_path)

    if not exist_class : continue

    for audio in os.listdir(class_path):

        audio_path = os.path.join(class_path , audio)

        if audio_path.endswith(".wav"):
            feature_extract(audio_path , label)
        


In [98]:
X

[array([-87.68073   ,  32.367313  ,  18.795725  ,  20.83221   ,
          6.9187093 ,   8.665346  ,   1.8102554 ,  -0.8350422 ,
         -9.5956    ,   3.6483002 ,   3.098236  ,   2.5674727 ,
          2.9523592 ,  13.060574  ,  -8.004191  ,   2.1134274 ,
          6.903523  ,  -7.372855  ,   8.16609   ,   1.2482636 ,
         -6.820781  ,   0.93029606,   2.0695515 ,  -2.141616  ,
         -1.2202514 ,  -1.1640085 ,   0.8280449 ,  -4.8603034 ,
          6.0890718 ,   4.147622  ,  -1.4324179 ,   4.7831717 ,
         -7.7453027 ,   0.35595116,   4.976658  ,   4.4150486 ,
          2.253983  ,   0.5425181 ,  -3.2647135 ,  -2.741783  ],
       dtype=float32),
 array([-77.878944  ,  52.35796   ,  -4.415205  ,  54.025364  ,
        -18.9887    ,  38.096817  , -20.184885  ,  27.20497   ,
        -32.275597  ,  18.620884  , -21.02858   ,  19.915928  ,
        -20.401493  ,  22.751     ,  -3.8538043 ,   6.843227  ,
         -5.137005  ,  13.52611   , -14.416107  ,  13.463621  ,
         -1.5600

In [99]:
from sklearn.preprocessing import LabelEncoder

In [100]:
le = LabelEncoder()
y = le.fit_transform(y)

In [101]:
le.classes_

array(['Abnormal Engine', 'Normal Engine'], dtype='<U15')

In [102]:
from sklearn.model_selection import train_test_split


In [103]:
X_train , X_test , y_train , y_test = train_test_split(X , y , test_size = 0.2 , random_state = 42)

In [104]:
y_train

array([1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0,
       1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1,
       1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0,
       1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0,
       1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1,
       0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0,
       1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1,
       1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1,
       0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1,
       0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0,
       0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0,
       0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1,

In [105]:
from sklearn.ensemble import RandomForestClassifier

In [106]:
rf = RandomForestClassifier()

In [107]:
rf.fit(X_train , y_train)

,"n_estimators n_estimators: int, default=100The number of trees in the forest... versionchanged:: 0.22 The default value of ``n_estimators`` changed from 10 to 100 in 0.22.",100
,"criterion criterion: {""gini"", ""entropy"", ""log_loss""}, default=""gini""The function to measure the quality of a split. Supported criteria are""gini"" for the Gini impurity and ""log_loss"" and ""entropy"" both for theShannon information gain, see :ref:`tree_mathematical_formulation`.Note: This parameter is tree-specific.",'gini'
,"max_depth max_depth: int, default=NoneThe maximum depth of the tree. If None, then nodes are expanded untilall leaves are pure or until all leaves contain less thanmin_samples_split samples.",None
,"min_samples_split min_samples_split: int or float, default=2The minimum number of samples required to split an internal node:- If int, then consider `min_samples_split` as the minimum number.- If float, then `min_samples_split` is a fraction and `ceil(min_samples_split * n_samples)` are the minimum number of samples for each split... versionchanged:: 0.18 Added float values for fractions.",2
,"min_samples_leaf min_samples_leaf: int or float, default=1The minimum number of samples required to be at a leaf node.A split point at any depth will only be considered if it leaves atleast ``min_samples_leaf`` training samples in each of the left andright branches. This may have the effect of smoothing the model,especially in regression.- If int, then consider `min_samples_leaf` as the minimum number.- If float, then `min_samples_leaf` is a fraction and `ceil(min_samples_leaf * n_samples)` are the minimum number of samples for each node... versionchanged:: 0.18 Added float values for fractions.",1
,"min_weight_fraction_leaf min_weight_fraction_leaf: float, default=0.0The minimum weighted fraction of the sum total of weights (of allthe input samples) required to be at a leaf node. Samples haveequal weight when sample_weight is not provided.",0.0
,"max_features max_features: {""sqrt"", ""log2"", None}, int or float, default=""sqrt""The number of features to consider when looking for the best split:- If int, then consider `max_features` features at each split.- If float, then `max_features` is a fraction and `max(1, int(max_features * n_features_in_))` features are considered at each split.- If ""sqrt"", then `max_features=sqrt(n_features)`.- If ""log2"", then `max_features=log2(n_features)`.- If None, then `max_features=n_features`... versionchanged:: 1.1 The default of `max_features` changed from `""auto""` to `""sqrt""`.Note: the search for a split does not stop until at least onevalid partition of the node samples is found, even if it requires toeffectively inspect more than ``max_features`` features.",'sqrt'
,"max_leaf_nodes max_leaf_nodes: int, default=NoneGrow trees with ``max_leaf_nodes`` in best-first fashion.Best nodes are defined as relative reduction in impurity.If None then unlimited number of leaf nodes.",None
,"min_impurity_decrease min_impurity_decrease: float, default=0.0A node will be split if this split induces a decrease of the impuritygreater than or equal to this value.The weighted impurity decrease equation is the following:: N_t / N * (impurity - N_t_R / N_t * right_impurity - N_t_L / N_t * left_impurity)where ``N`` is the total number of samples, ``N_t`` is the number ofsamples at the current node, ``N_t_L`` is the number of samples in theleft child, and ``N_t_R`` is the number of samples in the right child.``N``, ``N_t``, ``N_t_R`` and ``N_t_L`` all refer to the weighted sum,if ``sample_weight`` is passed... versionadded:: 0.19",0.0
,"bootstrap bootstrap: bool, default=TrueWhether bootstrap samples are used when building trees. If False, thewhole dataset is used to build each tree.",True
,"oob_score oob_score: bool or callable, default=FalseWhether to use out-of-bag samples to estimate the generalization score.By default, :func:`~sklearn.metrics.accuracy_score` is used.Provide a callable with signature `metric

In [108]:
y_pred = rf.predict(X_test)

In [109]:
y_pred

array([0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0,
       1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1,
       1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0,
       1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0,
       0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0])

In [110]:
from sklearn.metrics import accuracy_score , confusion_matrix

In [111]:
accu =  accuracy_score(y_pred , y_test)

In [112]:
accu

0.9453125

In [113]:
confusion_matrix(y_test , y_pred)

array([[56,  7],
       [ 0, 65]])

In [114]:
audio1 = r"C:\Users\Avi Mishra\OneDrive\Desktop\SAE\Normal Engine\normal_engine_idle_108.wav" #normal
audio2 = r"C:\Users\Avi Mishra\OneDrive\Desktop\Data_Fixed\Alternator Bearing Noise\Original\7_Alternator Bearing Noise_aug_99.wav" #fault
audio3 = r"C:\Users\Avi Mishra\OneDrive\Desktop\Data_Fixed\Valve tapping\Original\10_Valve tapping_aug_97.wav" #fault
audio4 = r"C:\Users\Avi Mishra\OneDrive\Desktop\SAE\Normal Engine\normal_engine_idle_146.wav"#normal
audio5 = r"C:\Users\Avi Mishra\OneDrive\Desktop\Data_Fixed\Engine kanocking\Original\4_Engine kanocking_aug_93.wav"#fault


In [169]:
audio_file_path = audio5

In [170]:
audio , sr = librosa.load(audio_file_path)

In [171]:
X_new = []

In [172]:
mfcc = librosa.feature.mfcc(
    y = audio,
    sr =sr,
    n_mfcc = 40
)
features = np.mean(mfcc , axis =1)
X_new.append(features)


In [173]:
y_pred_new = rf.predict(X_new)

In [174]:
if(y_pred_new == 0): print("Fault in Engine")
else: print("No fault in Engine")

Fault in Engine
